FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && apt-get install -y xz-utils
RUN apt-get install -y python3-pip
RUN apt-get install -y python3-webview
RUN apt-get install -y ffmpeg
